### ISSUE TITLE
i noticed a fatal flaw in this engine

### ISSUE THREAD

**Issue by rikokitsu** [FunkinModdingPlus/ModdingPlus#263]
and the fatal flaw is that i don't have commit perms
:trollface:

**Comment by FNFModdingPlusProjects** [comment]
:trollface:

**Comment by RafaelGiacom** [comment]
:trollface:

**Comment by GoMango99** [comment]
:trollface:

**Comment by FuseIsHere813** [comment]
"@TheDrawingCoder-Gamer closed this 2 days ago"

[https://github.githubassets.com/images/icons/emoji/trollface.png](url)
