### ISSUE TITLE
Bug Report: When I try to Compile it gives an error

### ISSUE THREAD

**Issue by LaCuevaDeipeLol** [FunkinModdingPlus/ModdingPlus#267]
When I try to compile in the latest version I get an error
source/LoadingState.hx:10: characters 20-22 : Expected )
![image](https://user-images.githubusercontent.com/88949308/129644279-deb810f3-a838-4d55-b144-cebccee8b183.png)

**Comment by Syro-nuke** [comment]
happened to me too
![image](https://user-images.githubusercontent.com/88434678/129902525-1e8e7263-b16e-426a-9fb1-49e8b3c1cfb0.png)

**Comment by Cluelessidiot8** [comment]
I don't even know how to compile it. Please help

**Comment by Pietrodjaowjao** [comment]
easy 2 fix, just see in the LoadingState.hx in the line 11 in some part need to put )
