### ISSUE TITLE
Bug Report: Game immediately closes when opened

### ISSUE THREAD

**Issue by keanu64github** [FunkinModdingPlus/ModdingPlus#291]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS
## What version of the game are you using? Look in the bottom left corner of the main menu.
Game not starting, but it is the latest patch as of 8/30/21 5:48 MDT
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![Screen Shot 2021-08-30 at 5 49 28 PM](https://user-images.githubusercontent.com/59621417/131419969-60357a19-2ce0-437f-819f-bdb7565ff1ee.png)
## Please describe your issue. Provide extensive detail and images if possible.
Game won't start even if the file is there.

**Comment by keanu64github** [comment]
@TheDrawingCoder-Gamer

**Comment by TheDrawingCoder-Gamer** [comment]
closing this just to piss you off :heart:

**Comment by TheDrawingCoder-Gamer** [comment]
but it looks like a file is missing, make sure you didn't just replace the exe. drag ur assets folder into the new assets folder from the new patch

**Comment by keanu64github** [comment]
I actually downloaded the lastest MAC version (complete) and still

**Comment by keanu64github** [comment]
> closing this just to piss you off ❤️

lol thx ur funny ;D
