### ISSUE TITLE
Bug Report: The Application Crashes when opened, even after fixing the "play.txt" bug with source code

### ISSUE THREAD

**Issue by keanu64github** [FunkinModdingPlus/ModdingPlus#304]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS 10.15.7 (19H512)
## What version of the game are you using? Look in the bottom left corner of the main menu.
Not starting up, but source code version is from the commit [poggers week 6 redone](https://github.com/FunkinModdingPlus/ModdingPlus/commit/759e49dcea9978c8e8d53633457b5a8962100402)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Change customPrecence in PlayState.hx to use the string 'Playin'
## Please describe your issue. Provide extensive detail and images if possible.

![Screen Shot 2021-09-14 at 19 07 56](https://user-images.githubusercontent.com/59621417/133353883-ffa22714-3d0d-4e58-8d66-4aff5cfa704a.png)

**Comment by SpookLad** [comment]
I'm having a similar issue, and it's really odd. I got rid of all of the stages in the original game, and replaced them with all new ones. Everything was working fine, nothing crashed, and I saw no issues.
Then I rebooted my pc, and now it crashes before even starting up every time. It's really odd.
I guess just don't get rid of the original stages or something.

**Comment by SpookLad** [comment]
Not sure why, but it turns out this can happen with weird code in the freeplaySongJson.jsonc
Do NOT try to use the delete song function in the in-game song sorter, especially if the song is at the end.
It will cause it to crash like this.

**Comment by SpookLad** [comment]
Every single time I think I've figured out what the issue is, it keeps crashing anyway
I know it has something to do with the freeplay code
I tried to replace the tutorial with endless, turns out the game doesn't like that, not sure why

**Comment by keanu64github** [comment]
@TheDrawingCoder-Gamer @FunkinModdingPlus nevermind
