### ISSUE TITLE
Suggestion: Custom Intro

### ISSUE THREAD

**Issue by TheGameBoyz** [FunkinModdingPlus/ModdingPlus#34]
# Please check for duplicates or similar issues before creating this issue.

## What is your suggestion, and why should it be implemented?

I think it would be cool to have a fully customizable intro (replace the newgrounds text and stuff)

**Comment by TheDrawingCoder-Gamer** [comment]
Progress is being done on this. The master branch can now pull custom creators.

**Comment by TheDrawingCoder-Gamer** [comment]
Idk about newgrounds logo... I know DJ added this
